from enum import StrEnum


class EntityType(StrEnum):
    PERSON = "PERSON"
    STARTUP = "STARTUP"
    COMPANY = "COMPANY"
    PRODUCT = "PRODUCT"
    APP = "APP"
    REPOSITORY = "REPOSITORY"
    ORGANIZATION = "ORGANIZATION"
    MEDIA_HOUSE = "MEDIA_HOUSE"
    TV_STATION = "TV_STATION"
    RADIO_STATION = "RADIO_STATION"
    PODCAST = "PODCAST"
    YOUTUBE_CHANNEL = "YOUTUBE_CHANNEL"
    UNIVERSITY = "UNIVERSITY"
    COMMUNITY = "COMMUNITY"
    EVENT = "EVENT"
    PUBLICATION = "PUBLICATION"
    AGENCY = "AGENCY"
    TOOL = "TOOL"


class RankingType(StrEnum):
    METRIC = "METRIC"
    INDEX = "INDEX"
    TREND = "TREND"


class EvidenceLevel(StrEnum):
    A = "A"
    B = "B"
    C = "C"
    D = "D"
    E = "E"


class UgandaRelation(StrEnum):
    UGANDAN_IN_UGANDA = "UGANDAN_IN_UGANDA"
    UGANDAN_DIASPORA = "UGANDAN_DIASPORA"
    UGANDA_BASED_NON_UGANDAN = "UGANDA_BASED_NON_UGANDAN"
    UGANDA_FOUNDED_ORGANIZATION = "UGANDA_FOUNDED_ORGANIZATION"
    UGANDA_OPERATING_ORGANIZATION = "UGANDA_OPERATING_ORGANIZATION"
    UGANDA_FOCUSED = "UGANDA_FOCUSED"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REJECTED = "REJECTED"


class RankingRunStatus(StrEnum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    PUBLISHED = "PUBLISHED"
    FAILED = "FAILED"
